# Generated by Django 4.0.4 on 2022-04-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commnent',
            options={'get_latest_by': 'date_added', 'ordering': ['-date_added'], 'permissions': (('view_future_post', 'Can view unpublished posts'),)},
        ),
    ]
