# Generated by Django 4.0.4 on 2022-04-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_view_future_post_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commnent',
            options={'get_latest_by': 'date_added', 'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'title', 'ordering': ['-date_added', 'title'], 'permissions': (('view_future_post', 'Can view unpublished posts'),)},
        ),
    ]
